<a href="https://colab.research.google.com/github/Navnidhi-gandhi07/UCS420--P/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2


In [ ]:
import numpy as np
a=np.array([0,1,2,3,4])
z=2+a
print(z)
y=3*a
s=a/2
print( y)
print(s)


[2 3 4 5 6]
[ 0  3  6  9 12]
[0.  0.5 1.  1.5 2. ]


Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:

import numpy as np
arr=np.array([1,2,3,6,4,5])
z=arr[::-1]
print(f"the reverse array is {z}")
x = np.array([1,2,3,4,5,1,2,1,1,1])
countx=np.bincount(x)
mostfrequentx=np.argmax(countx)
indexx=np.where(x==mostfrequentx)[0]
print("index",indexx)
print("most frequent element",mostfrequentx)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
county = np.bincount(y)
mostfrequent = np.max(county)
mostfrequentvalues = np.where(county == mostfrequent)[0]
indices = {val: np.where(y == val)[0] for val in mostfrequentvalues}
for val, index in indices.items():
   print(f"Value {val}  at indices: {index}")

print("Most frequent elements:", mostfrequentvalues)


the reverse array is [5 4 6 3 2 1]
index [0 5 7 8 9]
most frequent element 1
Value 1  at indices: [0 1 2]
Value 3  at indices: [4 8 9]
Most frequent elements: [1 3]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
index1=arr[0,1]
index2=arr[2,0]
print(index1,"\n",index2)


20 
 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np
navnidhi=np.linspace(10,100,25)
print(navnidhi.ndim)
print(navnidhi.shape)
print(navnidhi.dtype)
print(navnidhi.nbytes)

reshape=navnidhi.reshape(25,1)
print(reshape)
transpose=reshape.T
print("after transpose ", transpose)




1
(25,)
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
after transpose  [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
import numpy as np
ucs420=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
mean=np.mean(ucs420)
median=np.median(ucs420)
maximum=np.max(ucs420)
minimum=np.min(ucs420)
uniqueelements=np.unique(ucs420)
print(mean)
print(median)
print(maximum)
print(minimum)
print(uniqueelements)
reshaped=ucs420.reshape(4,3)
print(reshaped)
resized=np.resize(ucs420,(2,3))
print(resized)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
